# Generated by Django 3.2.16 on 2023-01-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='nis',
            field=models.IntegerField(null=True),
        ),
    ]
