# Generated by Django 3.2.16 on 2023-01-14 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus', '0002_data_nis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keterangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=3)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='keterangan',
        ),
        migrations.AlterField(
            model_name='data',
            name='nis',
            field=models.CharField(max_length=8),
        ),
        migrations.AddField(
            model_name='data',
            name='keterangan_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengurus.keterangan'),
        ),
    ]
