# Generated by Django 3.2.16 on 2023-01-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus', '0003_auto_20230114_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='cover',
            field=models.ImageField(null=True, upload_to='cover/'),
        ),
        migrations.AddField(
            model_name='data',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='keterangan',
            name='nama',
            field=models.CharField(max_length=4),
        ),
    ]
