# Generated by Django 3.2.16 on 2023-01-15 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus', '0004_auto_20230115_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='kelas',
        ),
        migrations.AddField(
            model_name='data',
            name='kelas_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengurus.kelas'),
        ),
    ]
