# Generated by Django 3.2.16 on 2023-01-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus', '0005_auto_20230115_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='proker',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='nama',
            field=models.TextField(max_length=10),
        ),
    ]
