# Generated by Django 3.2.16 on 2023-01-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus', '0006_auto_20230119_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='proker',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
