# Generated by Django 3.2.16 on 2023-01-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus', '0007_alter_data_proker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='nis',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='proker',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
