# Generated by Django 3.2.16 on 2023-01-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus', '0009_osis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='proker',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Osis',
        ),
    ]
