# Generated by Django 3.2.16 on 2023-01-23 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus', '0011_siswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mpk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=50)),
                ('jabatan', models.CharField(max_length=50)),
                ('proker', models.TextField(null=True)),
                ('cover', models.ImageField(null=True, upload_to='cover/')),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('kelas_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengurus.kelas')),
                ('keterangan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengurus.keterangan')),
            ],
        ),
    ]
