# Generated by Django 3.2.16 on 2023-01-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus', '0012_mpk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mpk',
        ),
    ]
