# Generated by Django 3.2.16 on 2023-01-23 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus', '0013_delete_mpk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='kelas_id',
            new_name='kelas',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='keterangan_id',
            new_name='keterangan',
        ),
    ]
